modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="lava_walker"
version="1.0.0"
displayName="LavaWalker Enchantment"
logoFile="examplemod.png"
authors="Mikn"
description='''
LavaWalker generates obsidians as you walk over
lava. Generated Obsidians melt into lava through
crying obsidians over time.
このModは溶岩渡りのエンチャントを追加します。バニラの
氷渡りのように溶岩の上を歩く時黒曜石を生成します。生成
された黒曜石は時間経過で泣く黒曜石を通して溶岩ブロック
に戻ります。
'''
[[dependencies.lava_walker]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lava_walker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"