modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="lava_walker"
version="0.6.1"
displayName="LavaWalker Enchantment"
updateJSONURL="https://gist.githubusercontent.com/MitsukiGoto/5e69f7aca24bb8730b876654f4ea40e1/raw/029be1e4778db4bffd345c9fcee022fa1c052f97/lava_walker_versions.json"
# logoFile="examplemod.png"
authors="Mikn"
description='''
This mod adds LavaWalker Enchantment which
creates obsidian block as you walk over the
lava. As time passes, created obsidian will
be lava through crying obsidian.
このModは溶岩渡りのエンチャントを追加します。バニラの
氷渡りのように溶岩の上を歩く時黒曜石を生成します。生成
された黒曜石は時間経過で泣く黒曜石を通して溶岩ブロック
に戻ります。
'''
[[dependencies.lava_walker]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lava_walker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"