modLoader = "javafml"
loaderVersion = "{loader_version_range}"
license = "MIT License"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
LavaWalker generates obsidians as you walk over
lava. Generated Obsidians melt into lava through
crying obsidians over time.
このModは溶岩渡りのエンチャントを追加します。バニラの
氷渡りのように溶岩の上を歩く時黒曜石を生成します。生成
された黒曜石は時間経過で泣く黒曜石を通して溶岩ブロック
に戻ります。
'''
[[dependencies.lava_walker]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.lava_walker]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
